[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/leads"
  to = "/.netlify/functions/leads"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
